dist: bionic
sudo: required

language: python

python:
  - 3.5
  - 3.6
  - 3.7

env:
  global:
    - ENVIRONMENT_NAME: test
  matrix:
    - DJANGO_VERSION=django111
    - DJANGO_VERSION=django20
    - DJANGO_VERSION=django21

before_install:
 - sudo apt-get update -y
 - sudo apt-get install -y poppler-utils

install:
    - pip install -r "./example/requirements_${DJANGO_VERSION}.txt"

script:
 - export PYTHONPATH=${PWD}:${PWD} && cd example && python manage.py test
