# Generated by Django 2.1 on 2018-11-07 20:35
import django.db.models.deletion
from django.db import migrations, models

import dj_field_filemanager.models
import dj_field_filemanager.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('file', models.FileField(max_length=255, storage=dj_field_filemanager.storage.OverwriteStorage(), upload_to=dj_field_filemanager.models._upload_to, verbose_name='File')),
                ('thumbnail', models.FileField(blank=True, max_length=255, null=True, storage=dj_field_filemanager.storage.OverwriteStorage(), upload_to=dj_field_filemanager.models._thumbnail_upload_to, verbose_name='Thumbnail')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='folder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.Project'),
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Folder'),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('name', 'folder')},
        ),
    ]
