# Generated by Django 2.1.15 on 2025-11-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20250425_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
